services:
  esplora:
    image: blockstream/esplora:latest
    platform: linux/amd64
    command: >
      /srv/explorer/electrs_bitcoin/bin/electrs
      --network regtest
      --daemon-dir /data/.bitcoin
      --daemon-rpc-addr bitcoind:18443
      --cookie user:password
      --http-addr 0.0.0.0:3002
      --cors '*'
      -vv
